site_name: Hongfu Sun Website
site_description: "Academic profile of Hongfu Sun, Senior Lecturer in Medical Imaging & AI at the University of Newcastle"
site_url: https://sunhongfu.github.io
# repo_url: https://github.com/sunhongfu/sunhongfu.github.io # this will add the GitHub icon in the nav bar
site_author: "Hongfu Sun"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - content.code.copy
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=aY5eZ54AAAAJ&hl=en
    - icon: fontawesome/brands/github
      link: https://github.com/sunhongfu
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-3436-7831
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hongfu-sun-64b567169
  generator: false

plugins:
  - search
  - rss:
      match_path: "news/.*"
      date_from_meta:
        as_creation: "date"
  - minify:
      minify_html: true


nav:
  - Home: index.md
  - CV: cv.md
  - Research: research.md
  - Publications: publications.md
  - Software: software.md
  - Teaching: teaching.md
  - Students: students.md
  - Talks: talks.md
  # - Awards & Honors: awards.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - assets/extra.css